name: First Workflow

on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hellow there"
      - name: Print Goodbye
        run: echo "Bye there"
